import {createApp, nextTick} from 'vue';
import PullRequestMergeForm from './PullRequestMergeForm.vue';

// Forkana: only the squash merge style is offered, and merging is a single step:
// the visible button submits the merge form, the server generates the merge message.
function makeMergeForm(overrides: Record<string, any> = {}) {
  return {
    baseLink: '/user2/repo1/pulls/1',
    textAutoMergeButtonWhenSucceed: 'when checks succeed',
    textAutoMergeWhenSucceed: 'auto merge when checks succeed',
    textAutoMergeCancelSchedule: 'cancel auto merge',
    textMergeCommitId: 'merge commit id',
    canMergeNow: true,
    allOverridableChecksOk: true,
    emptyCommit: false,
    pullHeadCommitID: 'abcdef0123456789',
    defaultMergeStyle: 'squash',
    hasPendingPullRequestMerge: false,
    hasPendingPullRequestMergeTip: '',
    mergeStyles: [
      {
        name: 'squash',
        allowed: true,
        textDoMerge: 'Merge change request',
        hideAutoMerge: true,
      },
    ],
    ...overrides,
  };
}

async function mountMergeForm(overrides: Record<string, any> = {}): Promise<HTMLElement> {
  window.config.pageData.pullRequestMergeForm = makeMergeForm(overrides);
  const root = document.createElement('div');
  document.body.append(root);
  createApp(PullRequestMergeForm).mount(root);
  await nextTick();
  return root;
}

test('merges in a single click', async () => {
  const root = await mountMergeForm();

  const form = root.querySelector<HTMLFormElement>('form.form-fetch-action');
  expect(form).toBeTruthy();
  expect(form.getAttribute('action')).toEqual('/user2/repo1/pulls/1/merge');

  // exactly one visible button, and it submits the merge form directly
  const buttons = root.querySelectorAll('button');
  expect(buttons).toHaveLength(1);
  const button = buttons[0];
  expect(button.getAttribute('type')).toEqual('submit');
  expect(button.getAttribute('name')).toEqual('do');
  expect(button.getAttribute('value')).toEqual('squash');
  expect(button.textContent.trim()).toEqual('Merge change request');

  // the merge commit message is generated by the server, it is never posted by the client
  expect(root.querySelector('[name="merge_title_field"]')).toBeNull();
  expect(root.querySelector('[name="merge_message_field"]')).toBeNull();
  expect(root.querySelector('textarea')).toBeNull();

  // only a single merge style is allowed, so no style dropdown is rendered
  expect(root.querySelector('.ui.dropdown')).toBeNull();

  const values = Object.fromEntries(
    Array.from(form.querySelectorAll<HTMLInputElement>('input'), (el) => [el.name, el.value]),
  );
  expect(values._csrf).toEqual(window.config.csrfToken);
  expect(values.head_commit_id).toEqual('abcdef0123456789');
  expect(values.merge_when_checks_succeed).toEqual('false');
  expect(values.force_merge).toEqual('false');
  expect(values.merge_commit_id).toBeUndefined();
});

test('schedules an auto merge in a single click when it can not merge now', async () => {
  const root = await mountMergeForm({
    canMergeNow: false,
    allOverridableChecksOk: false,
    mergeStyles: [
      {name: 'squash', allowed: true, textDoMerge: 'Merge change request', hideAutoMerge: false},
    ],
  });

  const buttons = root.querySelectorAll('button');
  expect(buttons).toHaveLength(1);
  expect(buttons[0].getAttribute('type')).toEqual('submit');
  expect(buttons[0].textContent).toContain('when checks succeed');

  const form = root.querySelector<HTMLFormElement>('form.form-fetch-action');
  const values = Object.fromEntries(
    Array.from(form.querySelectorAll<HTMLInputElement>('input'), (el) => [el.name, el.value]),
  );
  expect(values.merge_when_checks_succeed).toEqual('true');
  expect(values.force_merge).toEqual('false');
});
